### ISSUE TITLE
YAML Frontmatter in tutorials

### ISSUE THREAD

**Issue by ZacBlanco** [hortonworks/tutorials#44]
Because we convert tutorials to HTML with Jekyll (http://jekyllrb.com) it would be useful to include metadata at the top of each tutorial.

I plan on adding the following tags to the top of tutorials

| metadata tag | description | where utilized | 
|-----------|------------|------|
| `tutorial-version`| version tag for which current tutorial is compatible | inserted into html link to for button on tutorial footer |
|`tutorial-series` |series which tutorial is a part of | no current plans but I feel would be useful for organization in the future|
|`title` |pretty self explanatory here |no specific uses yet but alas something we can use to insert if we ever needed it. Also helpful to make an "official" title for some of the tutorials | 
| `tutorial-id` | This will be used to identify tutorial in hortonworks community connection | used when inserting data into links for tutorial footer|
| `intro-page` | true or false value | can be used to insert extra data in top/bottom of paragraph if needed - no current use |
| `components` | a string array of values which specifies the hdp/hdf components which are used in the tutorial. | no specific plans - but could be utilized on gh-pages? Definitely something that could be useful. |

The build script also needs to be modified to not add YAML frontmatter since all tutorials should already contain it after this fix.

@roberthryniewicz @james94 @racoss

**Comment by ZacBlanco** [comment]
This is a duplicate of #40 . That issue will be closed. This one will be the official one for tracking this change. See branch "#44-adding-tutorial-metdata"

**Comment by james94** [comment]
These tags look great. If I think of any others that would be beneficial, I'll let you know.

**Comment by james94** [comment]
Now that you've merged this update to build_tutorials.sh, I will update you.

**Comment by james94** [comment]
I found an issue in the tutorial Q & A Section of tutorials. I think this may be a YAML Frontmatter issue.

For the ask questions button, href="" has an error in the url. The url should be:
~~~
https://community.hortonworks.com/questions/ask.html?space=81&topics=tutorial-100&topics=hdp-2.4.0
~~~

I added tutorial-100 in the href above. The value appears as 100 instead of tutorial-100 after converting the markdown to html. 

![tag_error_askquestion](https://cloud.githubusercontent.com/assets/11840449/15380041/73713974-1d27-11e6-858a-84f6292393b6.png)
