### ISSUE TITLE
Azure users can't use banana Dashboard from Sentiment tutorial

### ISSUE THREAD

**Issue by ZacBlanco** [hortonworks/tutorials#6]
Because we have hardcoded sandbox.hortonworks.com into `default.json` from sentiment tutorial, unless users edit hosts on their host to point to the  Azure machine, then they won't be able to use the Dashboard.

We should replace the old `default.json` with an updated one from @abajwa-hw located at https://raw.githubusercontent.com/abajwa-hw/ambari-nifi-service/master/demofiles/default.json

**Comment by abajwa-hw** [comment]
Zac

Here is the “server” property line that needs to be changed in the .json file (near bottom of the file)

  "solr": {
    "server": "/solr/",
    "core_name": "tweets",
    "core_list": [
      "tweets"
    ],
    "global_params": "&df=id"
  }
}



On Feb 6, 2016, at 3:15 PM, Zac <notifications@github.com<mailto:notifications@github.com>> wrote:


Because we have hardcoded sandbox.hortonworks.com<http://sandbox.hortonworks.com> into default.json from sentiment tutorial, unless users edit hosts file for Azure machine, then they won't be able to use the Dashboard.

We should replace the old default.json with an updated one from @abajwa-hw<https://github.com/abajwa-hw> located at https://raw.githubusercontent.com/abajwa-hw/ambari-nifi-service/master/demofiles/default.json
